import { createFileRoute } from "@tanstack/react-router";
import report from "@/data/test-report.json";

export const Route = createFileRoute("/reliability")({
  head: () => ({
    meta: [
      { title: "System Reliability — GreenMirror" },
      {
        name: "description",
        content:
          "Live snapshot of GreenMirror's automated test suite: coverage, passing tests, and the core modules under test.",
      },
      { name: "robots", content: "noindex" },
    ],
  }),
  component: ReliabilityPage,
});

interface ModuleEntry {
  path: string;
  lines: number;
  functions: number;
  branches: number;
  covered: boolean;
}

function ReliabilityPage() {
  const r = report as {
    generatedAt: string;
    totals: { passed: number; failed: number; total: number; suites: number };
    overallCoverage: {
      lines: number;
      statements: number;
      functions: number;
      branches: number;
    };
    businessLogicCoverage: number;
    modules: ModuleEntry[];
    thresholds: { overallLines: number; businessLogicLines: number };
  };

  const passRate = r.totals.total > 0 ? (r.totals.passed / r.totals.total) * 100 : 0;
  const overallOk = r.overallCoverage.lines >= r.thresholds.overallLines;
  const businessOk = r.businessLogicCoverage >= r.thresholds.businessLogicLines;
  const date = new Date(r.generatedAt);
  const dateStr = isNaN(date.getTime())
    ? "—"
    : date.toLocaleString(undefined, {
        dateStyle: "medium",
        timeStyle: "short",
      });

  return (
    <main className="min-h-dvh bg-background text-foreground">
      <div
        className="fixed inset-0 -z-10 opacity-40 pointer-events-none"
        style={{
          background:
            "radial-gradient(at 70% 10%, oklch(0.3 0.08 152 / 0.35), transparent 60%)",
        }}
        aria-hidden
      />

      <div className="max-w-5xl mx-auto px-6 py-16 lg:py-20 space-y-12">
        <header>
          <span className="font-mono text-[10px] tracking-[0.3em] uppercase text-primary">
            Developer · Transparency
          </span>
          <h1 className="mt-3 text-4xl lg:text-5xl font-extrabold tracking-tight">
            System Reliability
          </h1>
          <p className="mt-3 text-muted-foreground max-w-2xl">
            A live snapshot of GreenMirror's automated test suite. Generated by
            <code className="mx-1 px-1.5 py-0.5 rounded bg-card/60 font-mono text-xs">
              npm run test:coverage
            </code>
            on every CI run.
          </p>
        </header>

        <section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <Stat
            label="Tests passed"
            value={`${r.totals.passed} / ${r.totals.total}`}
            sub={`${passRate.toFixed(1)}% pass rate`}
            tone={r.totals.failed === 0 ? "good" : "bad"}
          />
          <Stat
            label="Test suites"
            value={String(r.totals.suites)}
            sub="modules under test"
            tone="neutral"
          />
          <Stat
            label="Overall coverage"
            value={`${r.overallCoverage.lines.toFixed(1)}%`}
            sub={`Target ${r.thresholds.overallLines}%+`}
            tone={overallOk ? "good" : "warn"}
          />
          <Stat
            label="Business-logic coverage"
            value={`${r.businessLogicCoverage.toFixed(1)}%`}
            sub={`Target ${r.thresholds.businessLogicLines}%+`}
            tone={businessOk ? "good" : "warn"}
          />
        </section>

        <section className="rounded-2xl border border-border/60 bg-card/30 backdrop-blur p-7 space-y-4">
          <div className="flex items-baseline justify-between flex-wrap gap-2">
            <h2 className="text-xl font-bold tracking-tight">Coverage breakdown</h2>
            <span className="font-mono text-[10px] tracking-[0.25em] uppercase text-muted-foreground">
              Last run · {dateStr}
            </span>
          </div>
          <div className="grid sm:grid-cols-4 gap-3">
            <Bar label="Lines" pct={r.overallCoverage.lines} />
            <Bar label="Statements" pct={r.overallCoverage.statements} />
            <Bar label="Functions" pct={r.overallCoverage.functions} />
            <Bar label="Branches" pct={r.overallCoverage.branches} />
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold tracking-tight">Core modules tested</h2>
          {r.modules.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No coverage data yet. Run{" "}
              <code className="font-mono">npm run test:coverage</code> to generate it.
            </p>
          ) : (
            <ul className="rounded-2xl border border-border/60 bg-card/30 backdrop-blur divide-y divide-border/60 overflow-hidden">
              {r.modules.map((m) => (
                <li
                  key={m.path}
                  className="grid grid-cols-[1fr_auto_auto_auto] gap-4 items-center px-5 py-3.5 text-sm"
                >
                  <code className="font-mono text-xs text-foreground/90 truncate">
                    {m.path}
                  </code>
                  <span className="font-mono text-xs text-muted-foreground hidden sm:inline">
                    fn {m.functions.toFixed(0)}%
                  </span>
                  <span className="font-mono text-xs text-muted-foreground hidden sm:inline">
                    br {m.branches.toFixed(0)}%
                  </span>
                  <CoveragePill pct={m.lines} />
                </li>
              ))}
            </ul>
          )}
        </section>

        <section className="rounded-2xl border border-border/60 bg-card/30 backdrop-blur p-7 space-y-3">
          <h2 className="text-xl font-bold tracking-tight">Run it locally</h2>
          <pre className="bg-background/60 border border-border/60 rounded-lg p-4 font-mono text-xs overflow-x-auto">
            <code>{`npm test              # run the full suite once
npm run test:watch    # watch mode for development
npm run test:coverage # generate coverage + reliability report`}</code>
          </pre>
        </section>
      </div>
    </main>
  );
}

function Stat({
  label,
  value,
  sub,
  tone,
}: {
  label: string;
  value: string;
  sub: string;
  tone: "good" | "warn" | "bad" | "neutral";
}) {
  const toneClass =
    tone === "good"
      ? "text-primary"
      : tone === "warn"
        ? "text-amber-400"
        : tone === "bad"
          ? "text-destructive"
          : "text-foreground";
  return (
    <div className="rounded-2xl border border-border/60 bg-card/30 backdrop-blur p-5">
      <span className="font-mono text-[10px] tracking-[0.25em] uppercase text-muted-foreground">
        {label}
      </span>
      <div className={`mt-2 text-3xl font-extrabold tracking-tight tabular-nums ${toneClass}`}>
        {value}
      </div>
      <div className="mt-1 text-xs text-muted-foreground">{sub}</div>
    </div>
  );
}

function Bar({ label, pct }: { label: string; pct: number }) {
  const clamped = Math.max(0, Math.min(100, pct));
  return (
    <div>
      <div className="flex items-baseline justify-between mb-1.5">
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-muted-foreground">
          {label}
        </span>
        <span className="font-mono text-xs tabular-nums">{clamped.toFixed(1)}%</span>
      </div>
      <div
        className="h-1.5 rounded-full bg-border/40 overflow-hidden"
        role="progressbar"
        aria-valuenow={clamped}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-label={`${label} coverage`}
      >
        <div
          className="h-full bg-primary rounded-full transition-all"
          style={{ width: `${clamped}%` }}
        />
      </div>
    </div>
  );
}

function CoveragePill({ pct }: { pct: number }) {
  const tone =
    pct >= 80
      ? "bg-primary/15 text-primary border-primary/40"
      : pct >= 60
        ? "bg-amber-400/10 text-amber-300 border-amber-400/30"
        : "bg-destructive/10 text-destructive border-destructive/30";
  return (
    <span
      className={`inline-flex items-center justify-center min-w-14 px-2.5 py-1 rounded-full border text-xs font-mono tabular-nums ${tone}`}
    >
      {pct.toFixed(0)}%
    </span>
  );
}
